@startuml
'https://plantuml.com/sequence-diagram



autonumber 1.1.1
activate Visiteur
Visiteur -> Site_internet: saisie URL page inscription
Site_internet -> Visiteur: ok affiche page inscription

autonumber 2.1
activate Site_internet
Visiteur -> Site_internet: saisie mail/password et valide
Site_internet-> Site_internet: vérifie le formulaire
Site_internet -> database: cherche utilisateur avec username saisie


alt authentification acceptée

Site_internet->database: ajoute l'utilisateur en BDD
database->Site_internet: user créé
Site_internet->Visiteur: envoie email avec Token validation
Visiteur->Site_internet: click sur le lien de validation
Site_internet->database: recherche user par Token
alt utilisateur existe
Site_internet->database: supprime Token temporaire
Site_internet->Visiteur: renvoie vers la page d'accueil
else utlisateur n'existe pass
Site_internet->Visiteur : erreur
end
else authentifiaction rejetée
database->Site_internet : utilisteur existe déjà
Site_internet -> Visiteur: erreur

end

@enduml