@startuml
'https://plantuml.com/sequence-diagram

[o-> User: Connexion

autonumber

autonumber 1.1.1
User -> Site_internet: Demande suppression figure
activate User
autonumber 2.1
activate Site_internet
Site_internet -> database : Demande suppression figure
activate database
database -> Site_internet: Ok article supprimé


@enduml