@startuml
'https://plantuml.com/sequence-diagram


[o-> User: Connexion

autonumber 1.1.1
User -> Site_internet: Demande page figure
activate User
activate Site_internet
Site_internet-> User: affiche page figure avec les commentaire

autonumber 2.1
User->Site_internet: supprime son commentaire
activate database
Site_internet -> database : supprime le commentaire dans la BDD
database->Site_internet: ok commentaire supprimé

Site_internet -> User: affiche les commentaires
@enduml