@startuml
'https://plantuml.com/sequence-diagram

[o-> User: Connexion

autonumber 1.1.1
User -> Site_internet: Demande formulaire modification figure
activate User
activate Site_internet
Site_internet-> User: affiche le formulaire pré-rempli
User->Site_internet: modifie la figure et valide

autonumber 2.1.1

Site_internet -> database : envoie la modification
activate database
database -> Site_internet: Ok modification effectuée

@enduml